### ISSUE TITLE
Hot reloading doesn't work

### ISSUE THREAD

**Issue by dandv** [guybedford/jspm-beta-guide#7]
[The page](http://jspm.io/0.17-beta-guide/hot-reloading.html) reads

> Next edit the `jspm.browser.js` file

But there is no `jspm.browser.js` file, if you follow the steps from the previous chapters.

**Comment by guybedford** [comment]
Thanks, I've included in https://github.com/guybedford/jspm-beta-guide/commit/5ca0ce57a9fcdf4b997c94c3ef12a633f02561e8. Let me know if that covers it ok.

**Comment by dandv** [comment]
Thank you. I got hot reloading to work. However, often it takes saving several times for the browser to pick up the actual change. More details at https://github.com/jspm/jspm-cli/issues/2089#issuecomment-249438191.
